### ISSUE TITLE
Want a friendly link about this paper

### ISSUE THREAD

**Issue by HanwenQin** [weedegee/dsse#1]
I heard that you just implement Kamara's dsse scheme, so I wonder if you could  tell me the information about this paper, eg a link about this paper , .pdf of this paper or the whole name of this paper

**Comment by weedegee** [comment]
It's been a while but I'm fairly sure this was:

Seny Kamara, Charalampos Papamanthou, and Tom Roeder. 2012. Dynamic searchable symmetric encryption. In Proceedings of the 2012 ACM conference on Computer and communications security (CCS ’12). Association for Computing Machinery, New York, NY, USA, 965–976. DOI:https://doi.org/10.1145/2382196.2382298

**Comment by HanwenQin** [comment]
Great share,thanks a lot!
